version: '2.3'

services:

  bonus-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    networks:
      - internal
    depends_on:
      bonus-db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://bonus-db:5432/bonus
      - DB_USERNAME=bonus
      - DB_PASSWORD=bonus

  bonus-db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    networks:
      - internal
    environment:
      - POSTGRES_USER=bonus
      - POSTGRES_PASSWORD=bonus
      - POSTGRES_DB=bonus
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
networks:
  internal: