spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bonus}
    username: ${DB_USERNAME:bonus}
    password: ${DB_PASSWORD:bonus}